[package]
name = "boost_type_traits"
description = "Boost C++ library boost_type_traits packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_type_traits"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_type_traits"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_static_assert = { version = "0.1.0", path = "../boost_static_assert" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
